fos_user:
    db_driver: orm
    firewall_name: main
    user_class: MilesApart\AdminBundle\Entity\FosUser
    registration:
        form:
            type: miles_apart_user_registration
            validation_groups: [AcmeRegistration]
    profile:
        form:
            type: miles_apart_user_profile
            validation_groups: [AcmeProfile]