parameters:
#    miles_apart_public_user.example.class: MilesApart\PublicUserBundle\Example

services:
    logout_success_handler:
        class:  MilesApart\PublicUserBundle\Component\Authentication\Handler\LogoutSuccessHandler
#   miles_apart_public_user.example:
#        class: %miles_apart_public_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
