<?php

namespace MilesApart\BasketBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BasketProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BasketProductRepository extends EntityRepository
{
}
