<?php

namespace MilesApart\BasketBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RemovedBasketProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RemovedBasketProductRepository extends EntityRepository
{
}
