# You can specify a custom docker image from Docker Hub as your build environment
image: php:7.1.17

pipelines:
    branches:
        miles_apart_test:
            - step:
                script:
                    - apt-get update
                    - apt-get --assume-yes install curl git -y
                    - curl -LO https://deployer.org/deployer.phar
                    - mv deployer.phar /usr/local/bin/dep
                    - chmod +x /usr/local/bin/dep
                    - curl -LO https://getcomposer.org/composer.phar
                    - chmod +x ./composer.phar
                    - mv ./composer.phar /usr/local/bin/composer
                    - dep -f=./deploy/deploy.php deploy test
                    - composer dump-autoload --optimize --no-dev --classmap-authoritative
                    - sudo service apache2 restart
        miles_apart_live:
            - step:
                script:
                    - apt-get update
                    - apt-get --assume-yes install curl git -y
                    - curl -LO https://deployer.org/deployer.phar
                    - mv deployer.phar /usr/local/bin/dep
                    - chmod +x /usr/local/bin/dep
                    - curl -LO https://getcomposer.org/composer.phar
                    - chmod +x ./composer.phar
                    - mv ./composer.phar /usr/local/bin/composer
                    - dep -f=./deploy/deploy.php deploy production
                    - composer dump-autoload --optimize --no-dev --classmap-authoritative
                    - sudo service apache2 restart