miles_apart_staff_homepage:
    pattern:  /
    defaults: { _controller: MilesApartStaffBundle:Page:index }

miles_apart_staff_price_check:
    pattern:  /price-check
    defaults: { _controller: MilesApartStaffBundle:Page:pricecheck }

miles_apart_staff_price_check_submit:
    pattern:  /price-check/submit
    defaults: { _controller: MilesApartStaffBundle:Page:pricechecksubmit }

miles_apart_staff_record_sale:
    pattern:  /record-sale
    defaults: { _controller: MilesApartStaffBundle:Page:recordsale }

miles_apart_staff_record_sale_submit:
    pattern:  /record-sale/submit
    defaults: { _controller: MilesApartStaffBundle:Page:recordsalesubmit }

miles_apart_staff_record_return:
    pattern:  /record-return
    defaults: { _controller: MilesApartStaffBundle:Page:recordreturn }

miles_apart_staff_record_return_submit:
    pattern:  /record-return/submit
    defaults: { _controller: MilesApartStaffBundle:Page:recordreturnsubmit }

    
#*****************************************
# 
# Import routing
#
#*****************************************
MilesApartStaffBundle_staff-pickpack:
        resource: "@MilesApartStaffBundle/Resources/config/routing/staffpickpack.yml"
        prefix:   /pickpack

MilesApartStaffBundle_staff-products:
        resource: "@MilesApartStaffBundle/Resources/config/routing/staffproducts.yml"
        prefix:   /products

MilesApartStaffBundle_staff-transfer-requests:
        resource: "@MilesApartStaffBundle/Resources/config/routing/stafftransferrequests.yml"
        prefix:   /transfer-requests

MilesApartStaffBundle_staff-categories:
        resource: "@MilesApartStaffBundle/Resources/config/routing/staffcategories.yml"
        prefix:   /categories
        
MilesApartStaffBundle_staff-customers:
        resource: "@MilesApartStaffBundle/Resources/config/routing/staffcustomers.yml"
        prefix:   /customers

MilesApartStaffBundle_staff-campaigns:
        resource: "@MilesApartStaffBundle/Resources/config/routing/staffcampaigns.yml"
        prefix:   /campaigns

MilesApartStaffBundle_staff-finances:
        resource: "@MilesApartStaffBundle/Resources/config/routing/stafffinances.yml"
        prefix:   /finances

MilesApartStaffBundle_staff-business:
        resource: "@MilesApartStaffBundle/Resources/config/routing/staffbusiness.yml"
        prefix:   /business

MilesApartStaffBundle_staff-hr:
        resource: "@MilesApartStaffBundle/Resources/config/routing/staffhr.yml"
        prefix:   /hr

MilesApartStaffBundle_staff-purchase-orders:
        resource: "@MilesApartStaffBundle/Resources/config/routing/staffpurchaseorders.yml"
        prefix:   /purchase-orders

MilesApartStaffBundle_staff-website-management:
        resource: "@MilesApartStaffBundle/Resources/config/routing/staffwebsitemanagement.yml"
        prefix:   /website-management

MilesApartStaffBundle_staff-suppliers:
        resource: "@MilesApartStaffBundle/Resources/config/routing/staffsuppliers.yml"
        prefix:   /suppliers

MilesApartStaffBundle_staff-goods-in:
        resource: "@MilesApartStaffBundle/Resources/config/routing/staffgoodsin.yml"
        prefix:   /goods-in

MilesApartStaffBundle_staff-royalmail:
        resource: "@MilesApartStaffBundle/Resources/config/routing/staffroyalmail.yml"
        prefix:   /royal-mail

