<?php

namespace MilesApart\AdminBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BusinessPremisesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessPremisesRepository extends EntityRepository
{
	//Check the products for array match. (For CSV import)
	public function findBusinessPremisesNotAssignedDailyTake($dailyTakeDate)
	{
	 	
	 	$qb2 = $this->createQueryBuilder('daily_take_business_premises');
         $qb = $this->createQueryBuilder('business_premises');
/*
	 		$qb->from('MilesApartAdminBundle:BusinessPremises', 'bp')
   			->add('where', $qb->expr()->notIn('bp.id',
        		$qb2->select('DISTINCT(dtbp.business_premises_id)')
        		->from('MilesApartAdminBundle:DailyTakeBusinessPremises', 'dailytbp')
        		->innerJoin('MilesApartAdminBundle:BusinessPremises','bp2','WITH', 'dailytbp.business_premises_id')
    ));
*/
			$qb->from('MilesApartAdminBundle:BusinessPremisesType', 'bp')
   			->where('bp.id = :businessTypes')
   			->setParameter('businessTypes', '1')	;
        return $qb; 
   }

   //Check the products for array match. (For CSV import)
    public function getBusinessPremisesByStartAndEndDate($start_date, $end_date)
    {
        //Get Daily Take Business Premises WHERE daily_take_date is between start date and end date.
       /* $qb = $this->getEntityManager()
                        ->createQueryBuilder();
                        $qb->select('bp')
                        ->from('MilesApartAdminBundle:BusinessPremises', 'bp')
                        ->join('bp.daily_take_business_premises', 'dtbp')
                        ->join('dtbp.daily_take', 'dt')
                        ->where('dt.daily_take_date BETWEEN :start_date AND :end_date')
                        ->orderBy('dt.daily_take_date', 'ASC')
                        ->setParameter('start_date', $start_date)
                        ->setParameter('end_date', $end_date);
        */
        $query = $this->getEntityManager()
        ->createQuery('
            SELECT bp, dt, dtbp
            FROM MilesApartAdminBundle:BusinessPremises bp
            INNER JOIN bp.daily_take_business_premises dtbp
            INNER JOIN dtbp.daily_take dt
            WITH dt.daily_take_date BETWEEN :start_date AND :end_date
            ORDER BY dt.daily_take_date ASC'
         )->setParameter('start_date', $start_date)
        ->setParameter('end_date', $end_date);


        //Return result set.
        return $query
                  ->getResult(); 
   }
}
