<?php

namespace MilesApart\AdminBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DailyTakeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DailyTakeRepository extends EntityRepository
{
	//
	public function findDailyTakeByDate($dailyTakeDate)
	{
        //Check if there is a value for product id.
        if ($dailyTakeDate) {
                $query = $this->getEntityManager()
                    	->createQuery('
                    		SELECT p.id FROM MilesApartAdminBundle:DailyTake p
                            WHERE p.daily_take_date = :dailyTakeDate	
                    		')
                        ->setParameter('dailyTakeDate', $dailyTakeDate);
            } 
        return $query
                  ->getResult(); 
   }
}
