<?php

namespace MilesApart\AdminBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EmployeeStatutoryPaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeStatutoryPaymentRepository extends EntityRepository
{
	function getEmployeeStatutoryPaymentByStartAndEndDate($start_date, $end_date)
	{

		$query = $this->getEntityManager()
        ->createQuery('
            SELECT  esp, e
            FROM MilesApartAdminBundle:EmployeeStatutoryPayment esp 
            INNER JOIN esp.employee e 
            WITH esp.employee_statutory_payment_week_end_date
            BETWEEN :start_date AND :end_date
            ORDER BY e.employee_surname ASC'
         )->setParameter('start_date', $start_date)
        ->setParameter('end_date', $end_date);

        //Return result set.
        return $query
                  ->getResult(); 
   }
}
