<?php

namespace MilesApart\AdminBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ExpensesTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpensesTypeRepository extends EntityRepository
{
	//Check the products for array match. (For CSV import)
    public function getExpensesTypesByStartAndEndDate($start_date, $end_date)
    {

        $query = $this->getEntityManager()
        ->createQuery('
            SELECT  dtbppc, dt, dtbp, et
            FROM MilesApartAdminBundle:ExpensesType et
            INNER JOIN et.daily_take_business_premises_petty_cash dtbppc
            INNER JOIN dtbppc.daily_take_business_premises dtbp
            INNER JOIN dtbp.daily_take dt
            WITH dt.daily_take_date BETWEEN :start_date AND :end_date
            ORDER BY dt.daily_take_date ASC'
         )->setParameter('start_date', $start_date)
        ->setParameter('end_date', $end_date);

        //Return result set.
        return $query
                  ->getResult(); 
   }

	
}
