<?php

namespace MilesApart\AdminBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PrintRequestTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrintRequestTypeRepository extends EntityRepository
{
	//Check the products for array match. (For CSV import)
	public function getUnprintedPrintRequestTypes($price_type = null)
	{
        //Check if there is a value for product id.
        if ($price_type) {
            $query = $this->getEntityManager()
                	->createQuery('
                		SELECT prt, pr FROM MilesApartAdminBundle:PrintRequestType prt
                        JOIN prt.print_request pr
                        WHERE pr.print_request_printed is NULL	
                        AND prt.id = :price_type	
                        ORDER BY pr.print_request_date_created DESC
                		')
                    ->setParameter('price_type', $price_type);
        } else {
        	$query = $this->getEntityManager()
                	->createQuery('
                		SELECT prt, pr FROM MilesApartAdminBundle:PrintRequestType prt
                        JOIN prt.print_request pr
                        WHERE pr.print_request_printed is NULL	
                        ORDER BY pr.print_request_date_created DESC
                		');
        }
        return $query
                  ->getResult(); 
   }

}
