<?php

namespace MilesApart\AdminBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductPriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductPriceRepository extends EntityRepository
{
//Get current price from the data base including type and representatives.
	public function getCurrentPrice($product_id)
	{
        //Check if there is a value for product id.
        if ($product_id) {
                $query = $this->getEntityManager()
                    	->createQuery('
                    		SELECT pp, p FROM MilesApartAdminBundle:ProductPrice pp 
                    		LEFT JOIN pp.product p 
                            WHERE p.id = :product_id
                    		ORDER BY pp.product_price_valid_from ASC
                    		')
                        ->setParameter('product_id', $product_id);
            } 
        return $query
                  ->getResult(); 
   }

}
