<?php

namespace MilesApart\AdminBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductReviewRepository extends EntityRepository
{
	public function findUnapprovedReviews()
	{
        //Check if there is a value for product id.
        
        $query = $this->getEntityManager()
            	->createQuery('
            		SELECT pr FROM MilesApartAdminBundle:ProductReview pr 
                    WHERE pr.product_review_approved = FALSE
            		ORDER BY pr.product_review_date_created ASC
            		');
            
        return $query
                  ->getResult(); 
    }
}
