<?php

namespace MilesApart\AdminBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductQuestionRepository extends EntityRepository
{

	public function findUnansweredQuestions()
	{
        //Check if there is a value for product id.
        
        $query = $this->getEntityManager()
            	->createQuery('
            		SELECT pq FROM MilesApartAdminBundle:ProductQuestion pq 
                    WHERE pq.id NOT IN
					    (SELECT pa
					     FROM MilesApartAdminBundle:ProductAnswer pa WHERE pq = pa.product_question) 
            		ORDER BY pq.product_question_date_created ASC
            		');
            
        return $query
                  ->getResult(); 
    }
}
