<?php

namespace MilesApart\AdminBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionRepository extends EntityRepository
{
	//Retrive current promotion for vanity URL
	public function findCurrentPromotionByVanityUrl($vanity_url_append_text)
	{

        return $this->getEntityManager()
	        ->createQuery('
	            SELECT p FROM MilesApartAdminBundle:Promotion p   
                WHERE p.vanity_url_append_text = :vanity_url_append_text
                AND p.promotion_start_date <= CURRENT_DATE()
                AND (p.promotion_end_date >= CURRENT_DATE() OR p.promotion_end_date IS NULL)
	                ')
	        ->setParameter('vanity_url_append_text', $vanity_url_append_text)
	        ->setMaxResults(1)
	        ->getResult();
    
	}
}
