<?php

namespace MilesApart\AdminBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PurchaseOrderProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchaseOrderProductRepository extends EntityRepository
{
	//Check the products for array match. (For CSV import)
    public function findExistingPurchaseOrderProducts()
    {
    	//Find the id of the most recent incomplete transfer request
        //Check if there is a value for product id.
        
                $query = $this->getEntityManager()
                        ->createQuery('
                            SELECT pop FROM MilesApartAdminBundle:PurchaseOrderProduct pop
                            JOIN pop.product p
                            JOIN pop.purchase_order po
                            LEFT OUTER JOIN p.product_supplier ps
                            LEFT OUTER JOIN ps.supplier s
                            WHERE po.purchase_order_state = :purchase_order_state
                            ORDER BY p.product_supplier_code ASC
                            ')
                        ->setParameter('purchase_order_state', 1)
                        ;
            
        return $query
                  ->getResult(); 
   }

    
}
