<?php

namespace MilesApart\AdminBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReturnedProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReturnedProductRepository extends EntityRepository
{
	public function findReturnedProductByCustomerId($customer_id)
    {
        $query = $this->getEntityManager()
                        ->createQuery('
                            SELECT rp FROM MilesApartAdminBundle:ReturnedProduct rp
                            JOIN rp.customer_order_product cop
                            JOIN cop.customer_order co
                            JOIN co.customer c
                            JOIN cop.product p
                            WHERE c.id = :customer_id
                            
                            ')
                        ->setParameter('customer_id', $customer_id)
                        ;
            
        return $query
                  ->getResult(); 
    }
}
