<?php

namespace MilesApart\AdminBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SeasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeasonRepository extends EntityRepository
{
	//Check the products for array match. (For CSV import)
    public function findByCurrentDate()
    {
        //Get the season that is start date and end date straddles todays date
        $qb = $this->getEntityManager()
                        ->createQueryBuilder();
                        $qb->select('s')
                        ->from('MilesApartAdminBundle:Season', 's')
                        ->where('s.season_start_date < :today AND s.season_end_date > :today')
                        ->setParameter('today', new \DateTime());
                        
        
        $query = $qb->getQuery();

        //Return result set.
        return $query
                  ->getResult(); 
   }
}
