<?php
// src/MilesApart/AdminBundle/Entity/Repository/SupplierRepresentativeRepository.php

namespace MilesApart\AdminBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SupplierRepresentativeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierRepresentativeRepository extends EntityRepository
{

	 //Get alll supplier representatives.

    public function getAllSupplierRepresentatives()
    {

        $query = $this->getEntityManager()
                        ->createQuery('
                            SELECT sr FROM MilesApartAdminBundle:SupplierRepresentative sr 
                            
                            ORDER BY sr.supplier_representative_surname ASC
                            ');


        return $query
                  ->getResult();
   }

   //Get alll supplier representatives by supplier.

    public function getSupplierRepresentativesBySupplier($supplier_id)
    {

        $query = $this->getEntityManager()
                        ->createQuery('
                            SELECT sr FROM MilesApartAdminBundle:SupplierRepresentative sr 
                            WHERE sr.supplier_id = :id
                            ORDER BY sr.supplier_representative_start_date DESC
                            ')
                        ->setParameter('id', $supplier_id);

                        
        return $query
                  ->getResult();
   }

   public function findByLetters($string){
        return $this->getEntityManager()
        ->createQuery('
            SELECT sr FROM MilesApartAdminBundle:SupplierRepresentative sr  
                WHERE sr.supplier_representative_first_name LIKE :string 
                OR sr.supplier_representative_surname LIKE :string
                ')
                ->setParameter('string','%'.$string.'%')
                ->getResult();
    }
	
}