<?php
// src/MilesApart/AdminBundle/Entity/Repository/SupplierRepository.php

namespace MilesApart\AdminBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SupplierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierRepository extends EntityRepository
{
    //Get all suppliers from the data base including type and representatives.
	public function getAllSuppliers($supplier_type_id)
	{
        /*//Check if there is a value for supplier type and if so show only supplier that match id.
        if ($supplier_type_id) {
                $query = $this->getEntityManager()
                    	->createQuery('
                    		SELECT s, st, sr FROM MilesApartAdminBundle:Supplier s 
                    		LEFT JOIN s.supplier_type_id st 
                            LEFT JOIN s.supplier_representative_id sr
                            WHERE st.supplier_type_id = :supplier_type_id
                    		ORDER BY s.supplier_name ASC
                    		')
                        ->setParameter('supplier_type_id', $supplier_type_id);
            } else {
                $query = $this->getEntityManager()
                    ->createQuery('
                            SELECT s, st, sr FROM MilesApartAdminBundle:Supplier s 
                            LEFT JOIN s.supplier_type_id st 
                            LEFT JOIN s.supplier_representative_id sr
                            ORDER BY s.supplier_name ASC
                            ');
                        
            }
        return $query
                  ->getResult(); */
   }

   public function getSupplierAddress($supplier_id)
   {
        $query = $this->getEntityManager()
            ->createQuery('
                    SELECT s.supplier_name, s.supplier_address_1, s.supplier_address_2, s.supplier_town,
                    s.supplier_county, s.supplier_postcode, s.supplier_country FROM MilesApartAdminBundle:Supplier s
                    WHERE s.id = :supplier_id 
                    ')
            ->setParameter('supplier_id', $supplier_id)
            ;
                        
            
        return $query
                  ->getResult(); 
   }

   public function findAll()
    {
        return $this->findBy(array(), array('supplier_name' => 'ASC'));
    }

  
  public function findByLetters($string){
        return $this->getEntityManager()
        ->createQuery('
            SELECT s FROM MilesApartAdminBundle:Supplier s  
                WHERE s.supplier_name LIKE :string
                ')
                ->setParameter('string','%'.$string.'%')
                ->getResult();
    }

    
    public function findOneSupplierBy($supplier_id)
    {
        $query = $this->getEntityManager()
            ->createQuery('
                    SELECT s, po FROM MilesApartAdminBundle:Supplier s
                    LEFT JOIN s.purchase_order po
                    LEFT JOIN po.purchase_order_product pop
                    LEFT JOIN pop.product p
                    WHERE s.id = :supplier_id
                    ORDER BY po.id DESC

                    ')
            ->setParameter('supplier_id', $supplier_id)
            
            ;
                        
            
        return $query
                  ->getResult(); 
    }

  
}