<?php

namespace MilesApart\AdminBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TransferRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransferRequestRepository extends EntityRepository
{
	//Check the products for array match. (For CSV import)
    public function findExistingTransferRequest($business_premises)
    {
    	//Find the id of the most recent incomplete transfer request
        //Check if there is a value for product id.
        $qb = $this->createQueryBuilder('transfer_request');

        $qb->select('tr')
            ->from('MilesApartAdminBundle:TransferRequest', 'tr')
            ->join('tr.business_premises', 'bp', 'WITH', 'bp.id = tr.business_premises')
            ->where('bp.id = :business_premises')
            ->andWhere('tr.transfer_request_state = :transfer_request_state')
            ->setParameter('business_premises', $business_premises)
            ->setParameter('transfer_request_state', 1)
            ;
            
        $query = $qb->getQuery();
        return $query
                  ->getResult(\Doctrine\ORM\Query::HYDRATE_OBJECT); 
   }
}

