imports:
    - { resource: config_dev.yml }
    - { resource: parameters_test.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

sentry:
    dsn: "https://4de77a48094e4af0b118dc0826525279@sentry.io/1270580"
