imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: apc

session:
    cookie_lifetime: 86400
    gc_maxlifetime: 1800

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc



monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        firephp:
            type:  firephp
            level: info
        chromephp:
            type:  chromephp
            level: info
