miles_apart_seller:
    resource: "@MilesApartSellerBundle/Resources/config/routing.yml"
    prefix:   /
    schemes:  ['%httpProtocol%']

miles_apart_basket:
    resource: "@MilesApartBasketBundle/Resources/config/routing.yml"
    prefix:   /basket/
    schemes:  ['%httpProtocol%']

miles_apart_admin:
    resource: "@MilesApartAdminBundle/Resources/config/routing.yml"
    prefix:   /admin/
    defaults:  { _section:    admin }
    schemes:  ['%httpProtocol%']

miles_apart_staff:
    resource: "@MilesApartStaffBundle/Resources/config/routing.yml"
    prefix:   /staff/
    defaults:  { _section:    staff }
    schemes:  ['%httpProtocol%']

miles_apart_public_user:
        resource: "@MilesApartPublicUserBundle/Resources/config/routing.yml"
        schemes:  ['%httpProtocol%']

miles_apart_public:
    resource: "@MilesApartPublicBundle/Resources/config/routing.yml"
    prefix:   /
    defaults:  { _section:    public }
    schemes:  ['%httpProtocol%']

my_barcode_display:
    resource: "@MopaBarcodeBundle/Resources/config/routing/barcode_display.yml"
    prefix:   /mop/
    schemes:  ['%httpProtocol%']

_imagine:
    resource: .
    type:     imagine
    schemes:  ['%httpProtocol%']



oneup_uploader:
    resource: .
    type: uploader
    schemes:  ['%httpProtocol%']

snowcap_im:
  resource: "@SnowcapImBundle/Resources/config/routing.yml"
  schemes:  ['%httpProtocol%']

