<?php

namespace MilesApart\SellerBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AmazonOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AmazonOrderRepository extends EntityRepository
{
}
