parameters:
#    miles_apart_admin.example.class: MilesApart\AdminBundle\Example

services:
#    miles_apart_admin.example:
#        class: %miles_apart_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

  
