parameters:
#    miles_apart_basket.example.class: MilesApart\BasketBundle\Example

services:
#    miles_apart_basket.example:
#        class: %miles_apart_basket.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
