business:
    pattern:  /{page}
    defaults: { _controller: "MilesApartAdminBundle:Business:index", page: 1 }
    requirements:
        _method:  GET|POST
        page: \d+

business_show:
    pattern:  /{id}/show
    defaults: { _controller: "MilesApartAdminBundle:Business:show" }

business_new:
    pattern:  /new
    defaults: { _controller: "MilesApartAdminBundle:Business:new" }

business_create:
    pattern:  /create
    defaults: { _controller: "MilesApartAdminBundle:Business:create" }
    requirements: { _method: post }

business_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "MilesApartAdminBundle:Business:edit" }

business_update:
    pattern:  /{id}/update
    defaults: { _controller: "MilesApartAdminBundle:Business:update" }
    requirements: { _method: post|put }

business_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "MilesApartAdminBundle:Business:delete" }
    requirements: { _method: post|delete }
