business_competitor-type:
    pattern:  /{page}
    defaults: { _controller: "MilesApartAdminBundle:CompetitorType:index", page: 1 }
    requirements:
        _method:  GET|POST
        page: \d+

business_competitor-type_show:
    pattern:  /{id}/show
    defaults: { _controller: "MilesApartAdminBundle:CompetitorType:show" }

business_competitor-type_new:
    pattern:  /new
    defaults: { _controller: "MilesApartAdminBundle:CompetitorType:new" }

business_competitor-type_create:
    pattern:  /create
    defaults: { _controller: "MilesApartAdminBundle:CompetitorType:create" }
    requirements: { _method: post }

business_competitor-type_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "MilesApartAdminBundle:CompetitorType:edit" }

business_competitor-type_update:
    pattern:  /{id}/update
    defaults: { _controller: "MilesApartAdminBundle:CompetitorType:update" }
    requirements: { _method: post|put }

business_competitor-type_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "MilesApartAdminBundle:CompetitorType:delete" }
    requirements: { _method: post|delete }
