business_competitor-product:
    pattern:  /{page}
    defaults: { _controller: "MilesApartAdminBundle:CompetitorProduct:index", page: 1 }
    requirements:
        _method:  GET|POST
        page: \d+

business_competitor-product_show:
    pattern:  /{id}/show
    defaults: { _controller: "MilesApartAdminBundle:CompetitorProduct:show" }

business_competitor-product_new:
    pattern:  /new
    defaults: { _controller: "MilesApartAdminBundle:CompetitorProduct:new" }

business_competitor-product_create:
    pattern:  /create
    defaults: { _controller: "MilesApartAdminBundle:CompetitorProduct:create" }
    requirements: { _method: post }

business_competitor-product_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "MilesApartAdminBundle:CompetitorProduct:edit" }

business_competitor-product_update:
    pattern:  /{id}/update
    defaults: { _controller: "MilesApartAdminBundle:CompetitorProduct:update" }
    requirements: { _method: post|put }

business_competitor-product_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "MilesApartAdminBundle:CompetitorProduct:delete" }
    requirements: { _method: post|delete }
