customer_customer-opt-in-type:
    pattern:  /{page}
    defaults: { _controller: "MilesApartAdminBundle:CustomerOptInType:index", page: 1 }
    requirements:
        _method:  GET|POST
        page: \d+

customer_customer-opt-in-type_show:
    pattern:  /{id}/show
    defaults: { _controller: "MilesApartAdminBundle:CustomerOptInType:show" }

customer_customer-opt-in-type_new:
    pattern:  /new
    defaults: { _controller: "MilesApartAdminBundle:CustomerOptInType:new" }

customer_customer-opt-in-type_create:
    pattern:  /create
    defaults: { _controller: "MilesApartAdminBundle:CustomerOptInType:create" }
    requirements: { _method: post }

customer_customer-opt-in-type_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "MilesApartAdminBundle:CustomerOptInType:edit" }

customer_customer-opt-in-type_update:
    pattern:  /{id}/update
    defaults: { _controller: "MilesApartAdminBundle:CustomerOptInType:update" }
    requirements: { _method: post|put }

customer_customer-opt-in-type_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "MilesApartAdminBundle:CustomerOptInType:delete" }
    requirements: { _method: post|delete }
