customer-order_customer-order-state:
    pattern:  /{page}
    defaults: { _controller: "MilesApartAdminBundle:CustomerOrderState:index", page: 1 }
    requirements:
        _method:  GET|POST
        page: \d+

customer-order_customer-order-state_show:
    pattern:  /{id}/show
    defaults: { _controller: "MilesApartAdminBundle:CustomerOrderState:show" }

customer-order_customer-order-state_new:
    pattern:  /new
    defaults: { _controller: "MilesApartAdminBundle:CustomerOrderState:new" }

customer-order_customer-order-state_create:
    pattern:  /create
    defaults: { _controller: "MilesApartAdminBundle:CustomerOrderState:create" }
    requirements: { _method: post }

customer-order_customer-order-state_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "MilesApartAdminBundle:CustomerOrderState:edit" }

customer-order_customer-order-state_update:
    pattern:  /{id}/update
    defaults: { _controller: "MilesApartAdminBundle:CustomerOrderState:update" }
    requirements: { _method: post|put }

customer-order_customer-order-state_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "MilesApartAdminBundle:CustomerOrderState:delete" }
    requirements: { _method: post|delete }
