customer-order_customer-order-product:
    pattern:  /{page}
    defaults: { _controller: "MilesApartAdminBundle:CustomerOrderProduct:index", page: 1 }
    requirements:
        _method:  GET|POST
        page: \d+

customer-order_customer-order-product_show:
    pattern:  /{id}/show
    defaults: { _controller: "MilesApartAdminBundle:CustomerOrderProduct:show" }

customer-order_customer-order-product_new:
    pattern:  /new
    defaults: { _controller: "MilesApartAdminBundle:CustomerOrderProduct:new" }

customer-order_customer-order-product_create:
    pattern:  /create
    defaults: { _controller: "MilesApartAdminBundle:CustomerOrderProduct:create" }
    requirements: { _method: post }

customer-order_customer-order-product_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "MilesApartAdminBundle:CustomerOrderProduct:edit" }

customer-order_customer-order-product_update:
    pattern:  /{id}/update
    defaults: { _controller: "MilesApartAdminBundle:CustomerOrderProduct:update" }
    requirements: { _method: post|put }

customer-order_customer-order-product_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "MilesApartAdminBundle:CustomerOrderProduct:delete" }
    requirements: { _method: post|delete }
