customer_customer-interaction-type:
    pattern:  /{page}
    defaults: { _controller: "MilesApartAdminBundle:CustomerInteractionType:index", page:1 }
    requirements:
        _method:  GET|POST
        page: \d+

customer_customer-interaction-type_show:
    pattern:  /{id}/show
    defaults: { _controller: "MilesApartAdminBundle:CustomerInteractionType:show" }

customer_customer-interaction-type_new:
    pattern:  /new
    defaults: { _controller: "MilesApartAdminBundle:CustomerInteractionType:new" }

customer_customer-interaction-type_create:
    pattern:  /create
    defaults: { _controller: "MilesApartAdminBundle:CustomerInteractionType:create" }
    requirements: { _method: post }

customer_customer-interaction-type_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "MilesApartAdminBundle:CustomerInteractionType:edit" }

customer_customer-interaction-type_update:
    pattern:  /{id}/update
    defaults: { _controller: "MilesApartAdminBundle:CustomerInteractionType:update" }
    requirements: { _method: post|put }

customer_customer-interaction-type_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "MilesApartAdminBundle:CustomerInteractionType:delete" }
    requirements: { _method: post|delete }
