campaign_marketing-email:
    pattern:  /{page}
    defaults: { _controller: "MilesApartAdminBundle:MarketingEmail:index", page: 1 }
    requirements:
        _method:  GET|POST
        page: \d+

campaign_marketing-email_show:
    pattern:  /{id}/show
    defaults: { _controller: "MilesApartAdminBundle:MarketingEmail:show" }

campaign_marketing-email_new:
    pattern:  /new
    defaults: { _controller: "MilesApartAdminBundle:MarketingEmail:new" }

campaign_marketing-email_create:
    pattern:  /create
    defaults: { _controller: "MilesApartAdminBundle:MarketingEmail:create" }
    requirements: { _method: post }

campaign_marketing-email_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "MilesApartAdminBundle:MarketingEmail:edit" }

campaign_marketing-email_update:
    pattern:  /{id}/update
    defaults: { _controller: "MilesApartAdminBundle:MarketingEmail:update" }
    requirements: { _method: post|put }

campaign_marketing-email_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "MilesApartAdminBundle:MarketingEmail:delete" }
    requirements: { _method: post|delete }
