procurement_purchase-order-product:
    pattern:  /{page}
    defaults: { _controller: "MilesApartAdminBundle:PurchaseOrderProduct:index", page: 1 }
    requirements:
        _method:  GET|POST
        page: \d+

procurement_purchase-order-product_show:
    pattern:  /{id}/show
    defaults: { _controller: "MilesApartAdminBundle:PurchaseOrderProduct:show" }

procurement_purchase-order-product_new:
    pattern:  /new
    defaults: { _controller: "MilesApartAdminBundle:PurchaseOrderProduct:new" }

procurement_purchase-order-product_create:
    pattern:  /create
    defaults: { _controller: "MilesApartAdminBundle:PurchaseOrderProduct:create" }
    requirements: { _method: post }

procurement_purchase-order-product_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "MilesApartAdminBundle:PurchaseOrderProduct:edit" }

procurement_purchase-order-product_update:
    pattern:  /{id}/update
    defaults: { _controller: "MilesApartAdminBundle:PurchaseOrderProduct:update" }
    requirements: { _method: post|put }

procurement_purchase-order-product_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "MilesApartAdminBundle:PurchaseOrderProduct:delete" }
    requirements: { _method: post|delete }
