finance_supplier-invoice-product:
    pattern:  /{page}
    defaults: { _controller: "MilesApartAdminBundle:SupplierInvoiceProduct:index", page: 1 }
    requirements:
        _method:  GET|POST
        page: \d+

finance_supplier-invoice-product_show:
    pattern:  /{id}/show
    defaults: { _controller: "MilesApartAdminBundle:SupplierInvoiceProduct:show" }

finance_supplier-invoice-product_new:
    pattern:  /new
    defaults: { _controller: "MilesApartAdminBundle:SupplierInvoiceProduct:new" }

finance_supplier-invoice-product_create:
    pattern:  /create
    defaults: { _controller: "MilesApartAdminBundle:SupplierInvoiceProduct:create" }
    requirements: { _method: post }

finance_supplier-invoice-product_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "MilesApartAdminBundle:SupplierInvoiceProduct:edit" }

finance_supplier-invoice-product_update:
    pattern:  /{id}/update
    defaults: { _controller: "MilesApartAdminBundle:SupplierInvoiceProduct:update" }
    requirements: { _method: post|put }

finance_supplier-invoice-product_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "MilesApartAdminBundle:SupplierInvoiceProduct:delete" }
    requirements: { _method: post|delete }
