finance_supplier-invoice-state:
    pattern:  /{page}
    defaults: { _controller: "MilesApartAdminBundle:SupplierInvoiceState:index", page: 1 }
    requirements:
        _method:  GET|POST
        page: \d+

finance_supplier-invoice-state_show:
    pattern:  /{id}/show
    defaults: { _controller: "MilesApartAdminBundle:SupplierInvoiceState:show" }

finance_supplier-invoice-state_new:
    pattern:  /new
    defaults: { _controller: "MilesApartAdminBundle:SupplierInvoiceState:new" }

finance_supplier-invoice-state_create:
    pattern:  /create
    defaults: { _controller: "MilesApartAdminBundle:SupplierInvoiceState:create" }
    requirements: { _method: post }

finance_supplier-invoice-state_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "MilesApartAdminBundle:SupplierInvoiceState:edit" }

finance_supplier-invoice-state_update:
    pattern:  /{id}/update
    defaults: { _controller: "MilesApartAdminBundle:SupplierInvoiceState:update" }
    requirements: { _method: post|put }

finance_supplier-invoice-state_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "MilesApartAdminBundle:SupplierInvoiceState:delete" }
    requirements: { _method: post|delete }
