finance_supplier-invoice-payment:
    pattern:  /{page}
    defaults: { _controller: "MilesApartAdminBundle:SupplierInvoicePayment:index", page: 1 }
    requirements:
        _method:  GET|POST
        page: \d+

finance_supplier-invoice-payment_show:
    pattern:  /{id}/show
    defaults: { _controller: "MilesApartAdminBundle:SupplierInvoicePayment:show" }

finance_supplier-invoice-payment_new:
    pattern:  /new
    defaults: { _controller: "MilesApartAdminBundle:SupplierInvoicePayment:new" }

finance_supplier-invoice-payment_create:
    pattern:  /create
    defaults: { _controller: "MilesApartAdminBundle:SupplierInvoicePayment:create" }
    requirements: { _method: post }

finance_supplier-invoice-payment_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "MilesApartAdminBundle:SupplierInvoicePayment:edit" }

finance_supplier-invoice-payment_update:
    pattern:  /{id}/update
    defaults: { _controller: "MilesApartAdminBundle:SupplierInvoicePayment:update" }
    requirements: { _method: post|put }

finance_supplier-invoice-payment_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "MilesApartAdminBundle:SupplierInvoicePayment:delete" }
    requirements: { _method: post|delete }
