finance_supplier-payment-type:
    pattern:  /{page}
    defaults: { _controller: "MilesApartAdminBundle:SupplierPaymentType:index", page: 1 }
    requirements:
        _method:  GET|POST
        page: \d+

finance_supplier-payment-type_show:
    pattern:  /{id}/show
    defaults: { _controller: "MilesApartAdminBundle:SupplierPaymentType:show" }

finance_supplier-payment-type_new:
    pattern:  /new
    defaults: { _controller: "MilesApartAdminBundle:SupplierPaymentType:new" }

finance_supplier-payment-type_create:
    pattern:  /create
    defaults: { _controller: "MilesApartAdminBundle:SupplierPaymentType:create" }
    requirements: { _method: post }

finance_supplier-payment-type_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "MilesApartAdminBundle:SupplierPaymentType:edit" }

finance_supplier-payment-type_update:
    pattern:  /{id}/update
    defaults: { _controller: "MilesApartAdminBundle:SupplierPaymentType:update" }
    requirements: { _method: post|put }

finance_supplier-payment-type_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "MilesApartAdminBundle:SupplierPaymentType:delete" }
    requirements: { _method: post|delete }
