product_transfer-request-state:
    pattern:  /{page}
    defaults: { _controller: "MilesApartAdminBundle:TransferRequestState:index", page: 1 }
    requirements:
        _method:  GET|POST
        page: \d+

product_transfer-request-state_show:
    pattern:  /{id}/show
    defaults: { _controller: "MilesApartAdminBundle:TransferRequestState:show" }

product_transfer-request-state_new:
    pattern:  /new
    defaults: { _controller: "MilesApartAdminBundle:TransferRequestState:new" }

product_transfer-request-state_create:
    pattern:  /create
    defaults: { _controller: "MilesApartAdminBundle:TransferRequestState:create" }
    requirements: { _method: post }

product_transfer-request-state_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "MilesApartAdminBundle:TransferRequestState:edit" }

product_transfer-request-state_update:
    pattern:  /{id}/update
    defaults: { _controller: "MilesApartAdminBundle:TransferRequestState:update" }
    requirements: { _method: post|put }

product_transfer-request-state_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "MilesApartAdminBundle:TransferRequestState:delete" }
    requirements: { _method: post|delete }
